/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainPackage;

//import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class addStudents extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public addStudents() {
        initComponents();
        searchname.requestFocus();
        con = DBclass.connect();
        tableload();
    }

    public void tableload() {
        try {
            String q = "SELECT member_id,name,id,risk FROM members";
            pst = con.prepareStatement(q);
            rs = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {

        }
    }

    public void reset1() {
        tableload();
        midbox.setText("");
        riskbox.setText("");
        datebox.setText("YYYY-MM-DD");
        namebox.setText("Mr/ Miss/ Mrs....");
        idbox.setText("");
        addressbox.setText("");
        birthbox.setText("YYYY-MM-DD");
        contactbox.setText("+94");
        emailbox.setText("");
        detailsbox.setText("");
        searchname.setText("");
        searchid.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        riskbox = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        datebox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        idbox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addressbox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        birthbox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        contactbox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        emailbox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        detailsbox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        searchname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        searchid = new javax.swing.JTextField();
        refresh = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        midbox = new javax.swing.JLabel();
        midbox2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MEMBERS MAINTAINS");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Member ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 95, 78, 24));

        riskbox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        riskbox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(riskbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 93, 82, 24));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 139, 78, 24));

        datebox.setText("YYYY-MM-DD");
        datebox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateboxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateboxFocusLost(evt);
            }
        });
        datebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateboxActionPerformed(evt);
            }
        });
        datebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dateboxKeyPressed(evt);
            }
        });
        getContentPane().add(datebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 135, 374, 32));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 177, 78, 24));

        namebox.setText("Mr/ Miss/ Mrs....");
        namebox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameboxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameboxFocusLost(evt);
            }
        });
        namebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameboxActionPerformed(evt);
            }
        });
        namebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameboxKeyPressed(evt);
            }
        });
        getContentPane().add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 173, 374, 32));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ID No.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 215, 78, 24));

        idbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idboxActionPerformed(evt);
            }
        });
        idbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idboxKeyPressed(evt);
            }
        });
        getContentPane().add(idbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 211, 374, 32));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 253, 78, 24));

        addressbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressboxActionPerformed(evt);
            }
        });
        addressbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressboxKeyPressed(evt);
            }
        });
        getContentPane().add(addressbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 249, 374, 32));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Birth Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 291, 78, 24));

        birthbox.setText("YYYY-MM-DD");
        birthbox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                birthboxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                birthboxFocusLost(evt);
            }
        });
        birthbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthboxActionPerformed(evt);
            }
        });
        birthbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                birthboxKeyPressed(evt);
            }
        });
        getContentPane().add(birthbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 287, 374, 32));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Contact");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 329, 124, 24));

        contactbox.setText("+94");
        contactbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactboxActionPerformed(evt);
            }
        });
        contactbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contactboxKeyPressed(evt);
            }
        });
        getContentPane().add(contactbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 325, 374, 32));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Email");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 367, 124, 24));

        emailbox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailboxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailboxFocusLost(evt);
            }
        });
        emailbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailboxActionPerformed(evt);
            }
        });
        emailbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailboxKeyPressed(evt);
            }
        });
        getContentPane().add(emailbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 363, 374, 32));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Details");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 401, 124, 25));

        detailsbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsboxActionPerformed(evt);
            }
        });
        detailsbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                detailsboxKeyPressed(evt);
            }
        });
        getContentPane().add(detailsbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 401, 374, 97));

        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "NIC No", "Risk"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tableKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 103, 620, 540));

        add.setBackground(new java.awt.Color(0, 0, 0));
        add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addKeyPressed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 513, -1, -1));

        update.setBackground(new java.awt.Color(0, 0, 0));
        update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        update.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateKeyPressed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 513, -1, -1));

        delete.setBackground(new java.awt.Color(0, 0, 0));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        delete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deleteKeyPressed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 513, -1, -1));

        searchname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchnameActionPerformed(evt);
            }
        });
        searchname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchnameKeyPressed(evt);
            }
        });
        getContentPane().add(searchname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 583, 172, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 583, 73, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("ID");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 623, 25, 30));

        searchid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchidActionPerformed(evt);
            }
        });
        searchid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchidKeyPressed(evt);
            }
        });
        getContentPane().add(searchid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 623, 172, 30));

        refresh.setBackground(new java.awt.Color(0, 0, 0));
        refresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        refresh.setForeground(new java.awt.Color(255, 255, 255));
        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        refresh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                refreshKeyPressed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 513, -1, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("SEARCH");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 583, -1, -1));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("SEARCH");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 623, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Risk");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 93, 34, -1));

        midbox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        midbox.setForeground(new java.awt.Color(255, 0, 0));
        midbox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(midbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 95, 82, 24));

        midbox2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(midbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 95, 82, 24));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 670, 90, 20));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 303, 10, 40));

        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 53, 660, 620));

        jLabel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 53, 620, 620));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("*");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 133, 20, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("*");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 173, 20, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("*");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 213, 20, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("*");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 243, 20, 50));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("*");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 285, 20, 40));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("*");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 323, 20, 40));

        jLabel23.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel23.setText("INQUIRY TABLE");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 63, -1, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("MENU");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 13, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 204));
        jLabel24.setText(" ADD MEMBERS");
        jLabel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 150, 29));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dateboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateboxActionPerformed

    private void nameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameboxActionPerformed

    private void idboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idboxActionPerformed

    private void addressboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressboxActionPerformed

    private void birthboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthboxActionPerformed

    private void contactboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactboxActionPerformed

    private void emailboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailboxActionPerformed

    private void detailsboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailsboxActionPerformed

    private void searchnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchnameActionPerformed

    private void searchidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchidActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        String date = datebox.getText();
        String name = namebox.getText();
        String nic = idbox.getText();
        String address = addressbox.getText();
        String birthday = birthbox.getText();
        String contact = contactbox.getText();
        String email = emailbox.getText();
        String details = detailsbox.getText();

        if (!"Mr/ Miss/ Mrs....".equals(name) && !"".equals(nic) && !"YYYY-MM-DD".equals(date) && !"".equals(address) && !"YYYY-MM-DD".equals(birthday) && !"".equals(contact)) {
            int x = JOptionPane.showConfirmDialog(null, "CONFIRM MEMBER REGISTRATION ");
            if (x == 0) {
                try {

                    String q = "INSERT INTO members (membership_date,name,id,address,birthdate,contact,email,details) VALUES ('" + date + "','" + name + "','" + nic + "','" + address + "','" + birthday + "','" + contact + "','" + email + "','" + details + "')";
                    pst = con.prepareStatement(q);
                    pst.execute();
                    reset1();

                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_addActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

        int row = table.getSelectedRow();
        String member_id = table.getValueAt(row, 0).toString();

        try {
            String q = "SELECT * FROM members WHERE member_id= '" + member_id + "'";
            pst = con.prepareStatement(q);
            rs = pst.executeQuery();

            rs.next();
            midbox.setText(rs.getString("member_id"));
            riskbox.setText(rs.getString("risk"));
            datebox.setText(rs.getString("membership_date"));
            namebox.setText(rs.getString("name"));
            idbox.setText(rs.getString("id"));
            addressbox.setText(rs.getString("address"));
            birthbox.setText(rs.getString("birthdate"));
            contactbox.setText(rs.getString("contact"));
            emailbox.setText(rs.getString("email"));
            detailsbox.setText(rs.getString("details"));

        } catch (Exception e) {
            //System.out.println(e);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        String mid = midbox.getText();
        String date = datebox.getText();
        String name = namebox.getText();
        String nic = idbox.getText();
        String address = addressbox.getText();
        String birthday = birthbox.getText();
        String contact = contactbox.getText();
        String email = emailbox.getText();
        String details = detailsbox.getText();

        if (!"Mr/ Miss/ Mrs....".equals(name) && !"".equals(nic) && !"YYYY-MM-DD".equals(date) && !"".equals(address) && !"YYYY-MM-DD".equals(birthday) && !"".equals(contact)) {
            int x = JOptionPane.showConfirmDialog(null, "CONFIRM MEMBER UPDATION ");
            if (x == 0) {
                try {

                    String q = "UPDATE members SET membership_date='" + date + "',name='" + name + "',id= '" + nic + "',address='" + address + "',birthdate='" + birthday + "',contact='" + contact + "',email='" + email + "',details='" + details + "' WHERE member_id = '" + mid + "'";
                    pst = con.prepareStatement(q);
                    pst.execute();
                    reset1();

                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        reset1();

    }//GEN-LAST:event_refreshActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        String mid = midbox.getText();

        int x = JOptionPane.showConfirmDialog(null, "CONFIRM MEMBER DELETION ");
        if (x == 0) {
            try {

                PreparedStatement pst3 = con.prepareStatement("SELECT membership_date,name,id FROM members WHERE member_id = '" + mid + "'");
                rs = pst3.executeQuery();
                rs.next();
                String fromdate = rs.getString("membership_date");
                String membername = rs.getString("name");
                String nic = rs.getString("id");
                String sincedate = LocalDate.now().toString();

                PreparedStatement pst2 = con.prepareStatement("INSERT INTO deletedmember VALUES('" + membername + "','" + nic + "','" + fromdate + "','" + sincedate + "')");
                pst2.execute();

                String q = "DELETE FROM members WHERE member_id= '" + mid + "'";
                pst = con.prepareStatement(q);
                pst.execute();
                tableload();
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_deleteActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        String name = searchname.getText();
        try {
            String q = "SELECT member_id,name,id,risk FROM members WHERE name LIKE '%" + name + "%'";
            pst = con.prepareStatement(q);
            rs = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String id = searchid.getText();
        try {
            String q = "SELECT member_id,name,id,risk FROM members WHERE member_id LIKE '%" + id + "%'";
            pst = con.prepareStatement(q);
            rs = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void dateboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateboxFocusGained
        if (datebox.getText().equals("YYYY-MM-DD")) {
            datebox.setText("");

        }
    }//GEN-LAST:event_dateboxFocusGained

    private void dateboxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateboxFocusLost
        if (datebox.getText().equals("")) {
            datebox.setText("YYYY-MM-DD");

        }
    }//GEN-LAST:event_dateboxFocusLost

    private void birthboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_birthboxFocusGained
        if (birthbox.getText().equals("YYYY-MM-DD")) {
            birthbox.setText("");

        }
    }//GEN-LAST:event_birthboxFocusGained

    private void birthboxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_birthboxFocusLost
        if (birthbox.getText().equals("")) {
            birthbox.setText("YYYY-MM-DD");

        }
    }//GEN-LAST:event_birthboxFocusLost

    private void emailboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailboxFocusGained

    }//GEN-LAST:event_emailboxFocusGained

    private void emailboxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailboxFocusLost

    }//GEN-LAST:event_emailboxFocusLost

    private void nameboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameboxFocusGained
        if (namebox.getText().equals("Mr/ Miss/ Mrs....")) {
            namebox.setText("");

        }
    }//GEN-LAST:event_nameboxFocusGained

    private void nameboxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameboxFocusLost
        if (namebox.getText().equals("")) {
            namebox.setText("Mr/ Miss/ Mrs....");

        }
    }//GEN-LAST:event_nameboxFocusLost

    private void dateboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateboxKeyPressed

        int key = evt.getKeyCode();
        if (key == 10 || key == 40) {
            namebox.requestFocus();
        }

    }//GEN-LAST:event_dateboxKeyPressed

    private void nameboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameboxKeyPressed
        int key = evt.getKeyCode();
        if (key == 10 || key == 40) {
            idbox.requestFocus();
        } else if (key == 38) {
            datebox.requestFocus();
        }
    }//GEN-LAST:event_nameboxKeyPressed

    private void idboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idboxKeyPressed
        int key = evt.getKeyCode();
        if (key == 10 || key == 40) {
            addressbox.requestFocus();
        } else if (key == 38) {
            namebox.requestFocus();
        }
    }//GEN-LAST:event_idboxKeyPressed

    private void addressboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressboxKeyPressed
        int key = evt.getKeyCode();
        if (key == 10 || key == 40) {
            birthbox.requestFocus();
        } else if (key == 38) {
            idbox.requestFocus();
        }
    }//GEN-LAST:event_addressboxKeyPressed

    private void birthboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_birthboxKeyPressed
        int key = evt.getKeyCode();
        if (key == 10 || key == 40) {
            contactbox.requestFocus();
        } else if (key == 38) {
            addressbox.requestFocus();
        }
    }//GEN-LAST:event_birthboxKeyPressed

    private void contactboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactboxKeyPressed
        int key = evt.getKeyCode();
        if (key == 10 || key == 40) {
            emailbox.requestFocus();
        } else if (key == 38) {
            birthbox.requestFocus();
        }
    }//GEN-LAST:event_contactboxKeyPressed

    private void emailboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailboxKeyPressed
        int key = evt.getKeyCode();
        if (key == 10 || key == 40) {
            detailsbox.requestFocus();
        } else if (key == 38) {
            contactbox.requestFocus();
        }
    }//GEN-LAST:event_emailboxKeyPressed

    private void detailsboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detailsboxKeyPressed
        int key = evt.getKeyCode();
        if (key == 10) {
            add.requestFocus();
        } else if (key == 38) {
            emailbox.requestFocus();
        }
    }//GEN-LAST:event_detailsboxKeyPressed

    private void addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addKeyPressed
        int key = evt.getKeyCode();
        switch (key) {
            case 10:
                String date = datebox.getText();
                String name = namebox.getText();
                String nic = idbox.getText();
                String address = addressbox.getText();
                String birthday = birthbox.getText();
                String contact = contactbox.getText();
                String email = emailbox.getText();
                String details = detailsbox.getText();
                if (!"Mr/ Miss/ Mrs....".equals(name) && !"".equals(nic) && !"YYYY-MM-DD".equals(date) && !"".equals(address) && !"YYYY-MM-DD".equals(birthday) && !"".equals(contact)) {
                    int x = JOptionPane.showConfirmDialog(null, "CONFIRM MEMBER REGISTRATION ");
                    if (x == 0) {
                        try {

                            String q = "INSERT INTO members (membership_date,name,id,address,birthdate,contact,email,details) VALUES ('" + date + "','" + name + "','" + nic + "','" + address + "','" + birthday + "','" + contact + "','" + email + "','" + details + "')";
                            pst = con.prepareStatement(q);
                            pst.execute();
                            reset1();

                        } catch (Exception e) {
                        }
                    }
                }
                break;
            case 39:
                update.requestFocus();
                break;
            case 38:
                detailsbox.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_addKeyPressed

    private void updateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateKeyPressed
        int key = evt.getKeyCode();
        switch (key) {
            case 10:
                String mid = midbox.getText();
                String date = datebox.getText();
                String name = namebox.getText();
                String nic = idbox.getText();
                String address = addressbox.getText();
                String birthday = birthbox.getText();
                String contact = contactbox.getText();
                String email = emailbox.getText();
                String details = detailsbox.getText();
                if (!"Mr/ Miss/ Mrs....".equals(name) && !"".equals(nic) && !"YYYY-MM-DD".equals(date) && !"".equals(address) && !"YYYY-MM-DD".equals(birthday) && !"".equals(contact)) {
                    int x = JOptionPane.showConfirmDialog(null, "CONFIRM MEMBER UPDATION ");
                    if (x == 0) {
                        try {

                            String q = "UPDATE members SET membership_date='" + date + "',name='" + name + "',id= '" + nic + "',address='" + address + "',birthdate='" + birthday + "',contact='" + contact + "',email='" + email + "',details='" + details + "' WHERE member_id = '" + mid + "'";
                            pst = con.prepareStatement(q);
                            pst.execute();
                            reset1();

                        } catch (Exception e) {
                        }
                    }
                }
                break;
            case 39:
                delete.requestFocus();
                break;
            case 37:
                add.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_updateKeyPressed

    private void deleteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deleteKeyPressed

        int key = evt.getKeyCode();
        if (key == 10) {

            String mid = midbox.getText();

            int x = JOptionPane.showConfirmDialog(null, "CONFIRM MEMBER DELETION ");
            if (x == 0) {
                try {

                    PreparedStatement pst3 = con.prepareStatement("SELECT membership_date,name,id FROM members WHERE member_id = '" + mid + "'");
                    rs = pst3.executeQuery();
                    rs.next();
                    String fromdate = rs.getString("membership_date");
                    String membername = rs.getString("name");
                    String nic = rs.getString("id");
                    String sincedate = LocalDate.now().toString();

                    PreparedStatement pst2 = con.prepareStatement("INSERT INTO deletedmember VALUES('" + membername + "','" + nic + "','" + fromdate + "','" + sincedate + "')");
                    pst2.execute();

                    String q = "DELETE FROM members WHERE member_id= '" + mid + "'";
                    pst = con.prepareStatement(q);
                    pst.execute();
                    tableload();
                } catch (Exception e) {
                }
            }

        } else if (key == 39) {
            refresh.requestFocus();
        } else if (key == 37) {
            update.requestFocus();
        }
    }//GEN-LAST:event_deleteKeyPressed

    private void refreshKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_refreshKeyPressed
        int key = evt.getKeyCode();
        if (key == 10) {

            reset1();
        } else if (key == 37) {
            delete.requestFocus();
        } else if (key == 40) {
            searchname.requestFocus();
        }
    }//GEN-LAST:event_refreshKeyPressed

    private void searchnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchnameKeyPressed

        int key = evt.getKeyCode();
        if (key == 10) {

            String name = searchname.getText();
            try {
                String q = "SELECT member_id,name,id,risk FROM members WHERE name LIKE '%" + name + "%'";
                pst = con.prepareStatement(q);
                rs = pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
            }
        } else if (key == 40) {
            searchid.requestFocus();
        } else if (key == 38) {
            refresh.requestFocus();
        }
    }//GEN-LAST:event_searchnameKeyPressed

    private void searchidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchidKeyPressed

        int key = evt.getKeyCode();
        if (key == 10) {

            String id = searchid.getText();
            try {
                String q = "SELECT member_id,name,id,risk FROM members WHERE member_id LIKE '%" + id + "%'";
                pst = con.prepareStatement(q);
                rs = pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
            }

        } else if (key == 38) {
            searchname.requestFocus();
        }

    }//GEN-LAST:event_searchidKeyPressed

    private void tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyPressed


    }//GEN-LAST:event_tableKeyPressed

    private void tableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyTyped

    }//GEN-LAST:event_tableKeyTyped

    private void tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyReleased
        int key = evt.getKeyCode();
        if (key == 10) {

            int row = table.getSelectedRow();
            String member_id = table.getValueAt(row, 0).toString();

            try {
                String q = "SELECT * FROM members WHERE member_id= '" + member_id + "'";
                pst = con.prepareStatement(q);
                rs = pst.executeQuery();

                rs.next();
                midbox.setText(rs.getString("member_id"));
                riskbox.setText(rs.getString("risk"));
                datebox.setText(rs.getString("membership_date"));
                namebox.setText(rs.getString("name"));
                idbox.setText(rs.getString("id"));
                addressbox.setText(rs.getString("address"));
                birthbox.setText(rs.getString("birthdate"));
                contactbox.setText(rs.getString("contact"));
                emailbox.setText(rs.getString("email"));
                detailsbox.setText(rs.getString("details"));

            } catch (Exception e) {
                //System.out.println(e);
            }
        }
    }//GEN-LAST:event_tableKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //menu x=new menu();
        //x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField addressbox;
    private javax.swing.JTextField birthbox;
    private javax.swing.JTextField contactbox;
    private javax.swing.JTextField datebox;
    private javax.swing.JButton delete;
    private javax.swing.JTextField detailsbox;
    private javax.swing.JTextField emailbox;
    private javax.swing.JTextField idbox;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel midbox;
    private javax.swing.JLabel midbox2;
    private javax.swing.JTextField namebox;
    private javax.swing.JButton refresh;
    private javax.swing.JLabel riskbox;
    private javax.swing.JTextField searchid;
    private javax.swing.JTextField searchname;
    private javax.swing.JTable table;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
