/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainPackage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class deletedtables extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public deletedtables() {
        initComponents();
        con = DBclass.connect();
        table1load();
        table2load();
        table3load();
    }

    public void table1load() {
        try {
            String q = "SELECT * FROM deletedbook";
            pst = con.prepareStatement(q);
            rs = pst.executeQuery();
            table1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {

        }
    }

    public void table2load() {
        try {
            String q = "SELECT * FROM deletedmember";
            pst = con.prepareStatement(q);
            rs = pst.executeQuery();
            table2.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {

        }
    }

    public void table3load() {
        try {
            String q = "SELECT * FROM risk";
            pst = con.prepareStatement(q);
            rs = pst.executeQuery();
            table3.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            //System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        isbnbox = new javax.swing.JTextField();
        titlebox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        date1box = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        nicbox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        date2box = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        namebox1 = new javax.swing.JTextField();
        nicbox1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INQUIRY TABLES");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ISBN", "Title", "Author", "Date"
            }
        ));
        jScrollPane1.setViewportView(table1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 184, 530, 160));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("ISBN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 123, 51, 22));

        isbnbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnboxActionPerformed(evt);
            }
        });
        isbnbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                isbnboxKeyPressed(evt);
            }
        });
        getContentPane().add(isbnbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 123, 231, -1));

        titlebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleboxActionPerformed(evt);
            }
        });
        titlebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                titleboxKeyPressed(evt);
            }
        });
        getContentPane().add(titlebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 153, 231, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Title");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 153, 51, 22));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "NIC", "From", "Since"
            }
        ));
        jScrollPane2.setViewportView(table2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 181, 610, 470));

        date1box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date1boxActionPerformed(evt);
            }
        });
        date1box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                date1boxKeyPressed(evt);
            }
        });
        getContentPane().add(date1box, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 93, 231, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 93, 51, 22));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 93, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 123, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SEARCH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 153, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 123, 51, 22));

        namebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameboxActionPerformed(evt);
            }
        });
        namebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameboxKeyPressed(evt);
            }
        });
        getContentPane().add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 123, 231, -1));

        nicbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicboxActionPerformed(evt);
            }
        });
        nicbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nicboxKeyPressed(evt);
            }
        });
        getContentPane().add(nicbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 153, 231, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("NIC");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 153, 51, 22));

        date2box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date2boxActionPerformed(evt);
            }
        });
        date2box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                date2boxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                date2boxKeyReleased(evt);
            }
        });
        getContentPane().add(date2box, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 93, 231, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 93, 51, 22));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 93, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("SEARCH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 123, -1, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("SEARCH");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 153, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel23.setText("DELETED BOOK INQUIRY");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 57, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel24.setText("RISK UPDATION INQUIRY");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 370, -1, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1064, 254, 30, 100));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 670, 90, 10));

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "NIC", "Name", "Risk", "New Risk"
            }
        ));
        jScrollPane3.setViewportView(table3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 480, 530, 170));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 415, 51, 22));

        namebox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namebox1ActionPerformed(evt);
            }
        });
        namebox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namebox1KeyPressed(evt);
            }
        });
        getContentPane().add(namebox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 415, 231, -1));

        nicbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicbox1ActionPerformed(evt);
            }
        });
        nicbox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nicbox1KeyPressed(evt);
            }
        });
        getContentPane().add(nicbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 445, 231, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("NIC");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 445, 51, 22));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("SEARCH");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton7KeyPressed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 415, -1, -1));

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("SEARCH");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jButton8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton8KeyPressed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 445, -1, -1));

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setText("MENU");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText(" INQUIRY TABLES");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 170, 29));

        jLabel25.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel25.setText("DELETED MEMBER INQUIRY");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 57, -1, -1));

        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1200, 620));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 320, 20, 100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void isbnboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnboxActionPerformed

    private void titleboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleboxActionPerformed

    private void date1boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date1boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date1boxActionPerformed

    private void nameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameboxActionPerformed

    private void nicboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicboxActionPerformed

    private void date2boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date2boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date2boxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String date = date1box.getText();
        try {
            isbnbox.setText("");
            titlebox.setText("");

            pst = con.prepareStatement("SELECT * FROM deletedbook WHERE date LIKE '%" + date + "%'");
            rs = pst.executeQuery();
            table1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            //System.out.println(e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String isbn = isbnbox.getText();
        try {
            date1box.setText("");
            titlebox.setText("");
            pst = con.prepareStatement("SELECT * FROM deletedbook WHERE isbn LIKE '%" + isbn + "%'");
            rs = pst.executeQuery();
            table1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            //System.out.println(e);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String title = titlebox.getText();
        try {
            date1box.setText("");
            isbnbox.setText("");
            pst = con.prepareStatement("SELECT isbn,title,author,date FROM deletedbook WHERE title LIKE '%" + title + "%'");
            rs = pst.executeQuery();
            table1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            //System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void date1boxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_date1boxKeyPressed
        if (evt.getKeyCode() == 10) {
            String date = date1box.getText();
            try {
                isbnbox.setText("");
                titlebox.setText("");
                pst = con.prepareStatement("SELECT * FROM deletedbook WHERE date LIKE '%" + date + "%'");
                rs = pst.executeQuery();
                table1.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
                //System.out.println(e);
            }
        }
    }//GEN-LAST:event_date1boxKeyPressed

    private void isbnboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isbnboxKeyPressed

        if (evt.getKeyCode() == 10) {

            String isbn = isbnbox.getText();
            try {
                date1box.setText("");
                titlebox.setText("");
                pst = con.prepareStatement("SELECT * FROM deletedbook WHERE isbn LIKE '%" + isbn + "%'");
                rs = pst.executeQuery();
                table1.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
                //System.out.println(e);
            }

        }
    }//GEN-LAST:event_isbnboxKeyPressed

    private void titleboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleboxKeyPressed

        if (evt.getKeyCode() == 10) {

            String title = titlebox.getText();
            try {
                date1box.setText("");
                isbnbox.setText("");
                pst = con.prepareStatement("SELECT isbn,title,author,date FROM deletedbook WHERE title LIKE '%" + title + "%'");
                rs = pst.executeQuery();
                table1.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
                //System.out.println(e);
            }

        }
    }//GEN-LAST:event_titleboxKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String date = date2box.getText();
        try {
            namebox.setText("");
            nicbox.setText("");
            pst = con.prepareStatement("SELECT * FROM deletedmember WHERE sincedate LIKE '%" + date + "%'");
            rs = pst.executeQuery();
            table2.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            //System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void date2boxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_date2boxKeyPressed
        if (evt.getKeyCode() == 10) {

            String date = date2box.getText();
            try {
                namebox.setText("");
                nicbox.setText("");
                pst = con.prepareStatement("SELECT * FROM deletedmember WHERE sincedate LIKE '%" + date + "%'");
                rs = pst.executeQuery();
                table2.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
                //System.out.println(e);
            }

        }
    }//GEN-LAST:event_date2boxKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String name = namebox.getText();
        try {
            date2box.setText("");
            nicbox.setText("");
            pst = con.prepareStatement("SELECT * FROM deletedmember WHERE name LIKE '%" + name + "%'");
            rs = pst.executeQuery();
            table2.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            //System.out.println(e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void nameboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameboxKeyPressed
        if (evt.getKeyCode() == 10) {

            String name = namebox.getText();
            try {
                date2box.setText("");
                nicbox.setText("");
                pst = con.prepareStatement("SELECT * FROM deletedmember WHERE name LIKE '%" + name + "%'");
                rs = pst.executeQuery();
                table2.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
                //System.out.println(e);
            }
        }
    }//GEN-LAST:event_nameboxKeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        String nic = nicbox.getText();
        try {
            date2box.setText("");
            namebox.setText("");
            pst = con.prepareStatement("SELECT * FROM deletedmember WHERE nic LIKE '%" + nic + "%'");
            rs = pst.executeQuery();
            table2.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            //System.out.println(e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void nicboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicboxKeyPressed
        if (evt.getKeyCode() == 10) {

            String nic = nicbox.getText();
            try {
                date2box.setText("");
                namebox.setText("");
                pst = con.prepareStatement("SELECT * FROM deletedmember WHERE nic LIKE '%" + nic + "%'");
                rs = pst.executeQuery();
                table2.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
                //System.out.println(e);
            }

        }
    }//GEN-LAST:event_nicboxKeyPressed

    private void date2boxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_date2boxKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_date2boxKeyReleased

    private void namebox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namebox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namebox1ActionPerformed

    private void namebox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namebox1KeyPressed
        if (evt.getKeyCode() == 10) {

            String name = namebox1.getText();
            try {
                nicbox1.setText("");
                pst = con.prepareStatement("SELECT * FROM risk WHERE name LIKE '%" + name + "%'");
                rs = pst.executeQuery();
                table3.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
                //System.out.println(e);
            }

        }
    }//GEN-LAST:event_namebox1KeyPressed

    private void nicbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicbox1ActionPerformed

    private void nicbox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicbox1KeyPressed
        if (evt.getKeyCode() == 10) {
            String id = nicbox1.getText();
            try {
                namebox1.setText("");
                pst = con.prepareStatement("SELECT * FROM risk WHERE id LIKE '%" + id + "%'");
                rs = pst.executeQuery();
                table3.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
                //System.out.println(e);
            }
        }
    }//GEN-LAST:event_nicbox1KeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String name = namebox1.getText();
        try {
            nicbox1.setText("");
            pst = con.prepareStatement("SELECT * FROM risk WHERE name LIKE '%" + name + "%'");
            rs = pst.executeQuery();
            table3.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            //System.out.println(e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton7KeyPressed

    }//GEN-LAST:event_jButton7KeyPressed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String id = nicbox1.getText();
        try {
            namebox1.setText("");
            pst = con.prepareStatement("SELECT * FROM risk WHERE id LIKE '%" + id + "%'");
            rs = pst.executeQuery();
            table3.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            //System.out.println(e);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton8KeyPressed

    }//GEN-LAST:event_jButton8KeyPressed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //menu x=new menu();
        //x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deletedtables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deletedtables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deletedtables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deletedtables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deletedtables().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date1box;
    private javax.swing.JTextField date2box;
    private javax.swing.JTextField isbnbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField namebox;
    private javax.swing.JTextField namebox1;
    private javax.swing.JTextField nicbox;
    private javax.swing.JTextField nicbox1;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JTextField titlebox;
    // End of variables declaration//GEN-END:variables
}
