/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainPackage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class issue extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public issue() {
        initComponents();
        midbox.requestFocus();
        membercheck.setVisible(false);
        bookcheck.setVisible(false);
        con = DBclass.connect();
        tableload();
    }

    public void tableload() {
        try {
            String q = "SELECT book_id,book_title,member_id,member_name,issue_date,return_date FROM issue";
            pst = con.prepareStatement(q);
            rs = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            massege.setText("Something Went Wrong");
        }
    }

    public void reset() {

        membercheck.setSelected(false);
        bookcheck.setSelected(false);
        membercheck.setVisible(false);
        bookcheck.setVisible(false);
        midbox.setText("");
        name.setText("");
        nic.setText("");
        risk.setText("");
        bidbox.setText("");
        title.setText("");
        isbn.setText("");
        issuedatebox.setText("YYYY-MM-DD");
        returndatebox.setText("YYYY-MM-DD");
        detailsbox.setText("");
        massege.setText("");

        tableload();
        searchname.setText("");
        searchtitle.setText("");
        searchissuedate.setText("");
        searchreturndate.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        midbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nic = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        risk = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        isbn = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bidbox = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        issuedatebox = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        returndatebox = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        detailsbox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        issue = new javax.swing.JButton();
        bookcheck = new javax.swing.JCheckBox();
        membercheck = new javax.swing.JCheckBox();
        massege = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        searchtitle = new javax.swing.JTextField();
        searchname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        searchreturndate = new javax.swing.JTextField();
        searchissuedate = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ISSUE BOOKS");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Member ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 109, 74, 28));

        midbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midboxActionPerformed(evt);
            }
        });
        midbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                midboxKeyPressed(evt);
            }
        });
        getContentPane().add(midbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 109, 210, 28));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Member Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 149, -1, 28));

        name.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 149, 210, 28));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("NIC");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 189, 28, 28));

        nic.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 189, 210, 28));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Risk");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 189, 28, 28));

        risk.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(risk, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 189, 40, 28));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Member Details");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 66, 330, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Book Details");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 275, 330, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Title");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 357, -1, 28));

        title.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 357, 250, 28));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("ISBN");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 397, 61, 28));

        isbn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 397, 250, 28));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Book ID");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 317, 61, 28));

        bidbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidboxActionPerformed(evt);
            }
        });
        bidbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bidboxKeyPressed(evt);
            }
        });
        getContentPane().add(bidbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 317, 250, 28));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Issue Date");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 473, 61, 28));

        issuedatebox.setText("YYYY-MM-DD");
        issuedatebox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                issuedateboxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                issuedateboxFocusLost(evt);
            }
        });
        issuedatebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedateboxActionPerformed(evt);
            }
        });
        issuedatebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                issuedateboxKeyPressed(evt);
            }
        });
        getContentPane().add(issuedatebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 473, 250, 28));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Return Date");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 513, -1, 28));

        returndatebox.setText("YYYY-MM-DD");
        returndatebox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                returndateboxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                returndateboxFocusLost(evt);
            }
        });
        returndatebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returndateboxActionPerformed(evt);
            }
        });
        returndatebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                returndateboxKeyPressed(evt);
            }
        });
        getContentPane().add(returndatebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 513, 250, 28));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Details");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 563, -1, 28));

        detailsbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsboxActionPerformed(evt);
            }
        });
        detailsbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                detailsboxKeyPressed(evt);
            }
        });
        getContentPane().add(detailsbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 553, 250, 66));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Book ID", "Book Title", "Member ID", "Member Name", "Issue Date", "Return Date"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 259, 830, 380));

        jLabel23.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel23.setText("INQUIRY TABLE");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 213, -1, -1));

        clear.setBackground(new java.awt.Color(0, 0, 0));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        clear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clearKeyPressed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 643, -1, -1));

        issue.setBackground(new java.awt.Color(0, 0, 0));
        issue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        issue.setForeground(new java.awt.Color(255, 255, 255));
        issue.setText("ISSUE");
        issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueActionPerformed(evt);
            }
        });
        issue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                issueKeyPressed(evt);
            }
        });
        getContentPane().add(issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 643, -1, -1));

        bookcheck.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookcheck.setText("Book Validation");
        getContentPane().add(bookcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 437, -1, -1));

        membercheck.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        membercheck.setText("Member Validation");
        getContentPane().add(membercheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 225, -1, -1));
        getContentPane().add(massege, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 643, 140, 22));

        jLabel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 53, 390, 630));

        jLabel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 53, 890, 630));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("*");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 513, 20, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("*");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 103, 20, 40));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("*");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 323, 20, 20));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("*");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 473, 30, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Book Title");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 143, 70, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Member Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 93, 100, 30));

        searchtitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtitleActionPerformed(evt);
            }
        });
        searchtitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchtitleKeyPressed(evt);
            }
        });
        getContentPane().add(searchtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 143, 240, 30));

        searchname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchnameActionPerformed(evt);
            }
        });
        searchname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchnameKeyPressed(evt);
            }
        });
        getContentPane().add(searchname, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 93, 240, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Return Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 143, 70, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Issue Date");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 93, 100, 30));

        searchreturndate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchreturndateActionPerformed(evt);
            }
        });
        searchreturndate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchreturndateKeyPressed(evt);
            }
        });
        getContentPane().add(searchreturndate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 143, 240, 30));

        searchissuedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchissuedateActionPerformed(evt);
            }
        });
        searchissuedate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchissuedateKeyPressed(evt);
            }
        });
        getContentPane().add(searchissuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 93, 240, 30));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("MENU");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText(" ISSUE BOOKS");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 130, 29));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void midboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midboxActionPerformed

    private void bidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bidboxActionPerformed

    private void issuedateboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedateboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issuedateboxActionPerformed

    private void returndateboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returndateboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returndateboxActionPerformed

    private void detailsboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailsboxActionPerformed

    private void issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueActionPerformed

        String book_id = bidbox.getText();
        String book_title = title.getText();
        String member_id = midbox.getText();
        String member_name = name.getText();
        String issue_date = issuedatebox.getText();
        String return_date = returndatebox.getText();
        String details = detailsbox.getText();

        if (membercheck.isSelected() && bookcheck.isSelected()) {
            if (!"YYYY-MM-DD".equals(issue_date) && !"YYYY-MM-DD".equals(return_date)) {
                massege.setText("");
                int x = JOptionPane.showConfirmDialog(null, "CONFIRM ISSUENCE");
                if (x == 0) {

                    String q = "INSERT INTO issue VALUES ('" + book_id + "','" + book_title + "','" + member_id + "','" + member_name + "','" + issue_date + "','" + return_date + "','" + details + "')";
                    try {
                        pst = con.prepareStatement(q);
                        pst.execute();
                        tableload();
                        reset();

                        pst = con.prepareStatement("DELETE FROM availablility WHERE book_id='" + book_id + "'");
                        pst.execute();

                    } catch (Exception e) {
                        massege.setText("Something Went Wrong");
                    }
                }
            } else {
                massege.setText("Please Enter Dates");
            }
        } else {
            massege.setText("Validation Failed");
        }
    }//GEN-LAST:event_issueActionPerformed

    private void midboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_midboxKeyPressed

        String member_id = midbox.getText();
        int key = evt.getKeyCode();
        if (key == 10) {
            try {
                String q = "SELECT name,id,risk FROM members WHERE member_id='" + member_id + "'";
                pst = con.prepareStatement(q);
                rs = pst.executeQuery();
                rs.next();
                String r = rs.getString("risk");
                name.setText(rs.getString("name"));
                nic.setText(rs.getString("id"));
                risk.setText(r);
                membercheck.setVisible(true);
                bidbox.requestFocus();

            } catch (Exception e) {
                name.setText("");
                nic.setText("");
                risk.setText("");
                membercheck.setSelected(false);
                membercheck.setVisible(false);

            }
        }
    }//GEN-LAST:event_midboxKeyPressed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed

        reset();

    }//GEN-LAST:event_clearActionPerformed

    private void bidboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bidboxKeyPressed

        String book_id = bidbox.getText();
        int key = evt.getKeyCode();
        if (key == 10) {
            try {
                String q = "SELECT isbn,title FROM availablility WHERE book_id='" + book_id + "'";
                pst = con.prepareStatement(q);
                rs = pst.executeQuery();
                rs.next();
                isbn.setText(rs.getString("isbn"));
                title.setText(rs.getString("title"));

                bookcheck.setVisible(true);
                issuedatebox.requestFocus();
            } catch (Exception e) {
                title.setText("");
                isbn.setText("");

                bookcheck.setSelected(false);
                bookcheck.setVisible(false);

            }
        }


    }//GEN-LAST:event_bidboxKeyPressed

    private void issuedateboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issuedateboxFocusGained

        if (issuedatebox.getText().equals("YYYY-MM-DD")) {
            issuedatebox.setText("");

        }
    }//GEN-LAST:event_issuedateboxFocusGained

    private void issuedateboxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issuedateboxFocusLost

        if (issuedatebox.getText().equals("")) {
            issuedatebox.setText("YYYY-MM-DD");

        }
    }//GEN-LAST:event_issuedateboxFocusLost

    private void returndateboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_returndateboxFocusGained

        if (returndatebox.getText().equals("YYYY-MM-DD")) {
            returndatebox.setText("");

        }

    }//GEN-LAST:event_returndateboxFocusGained

    private void returndateboxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_returndateboxFocusLost

        if (returndatebox.getText().equals("")) {
            returndatebox.setText("YYYY-MM-DD");

        }
    }//GEN-LAST:event_returndateboxFocusLost

    private void issuedateboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_issuedateboxKeyPressed

        if (evt.getKeyCode() == 10 || evt.getKeyCode() == 40) {
            returndatebox.requestFocus();
        }

    }//GEN-LAST:event_issuedateboxKeyPressed

    private void returndateboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_returndateboxKeyPressed

        if (evt.getKeyCode() == 10 || evt.getKeyCode() == 40) {
            detailsbox.requestFocus();
        } else if (evt.getKeyCode() == 38) {
            issuedatebox.requestFocus();
        }

    }//GEN-LAST:event_returndateboxKeyPressed

    private void detailsboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detailsboxKeyPressed

        if (evt.getKeyCode() == 38) {
            returndatebox.requestFocus();
        } else if (evt.getKeyCode() == 10) {
            issue.requestFocus();
        }
    }//GEN-LAST:event_detailsboxKeyPressed

    private void issueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_issueKeyPressed
        int key = evt.getKeyCode();
        if (key == 38) {
            detailsbox.requestFocus();
        } else if (key == 37) {
            clear.requestFocus();
        } else if (key == 10) {

            String book_id = bidbox.getText();
            String book_title = title.getText();
            String member_id = midbox.getText();
            String member_name = name.getText();
            String issue_date = issuedatebox.getText();
            String return_date = returndatebox.getText();
            String details = detailsbox.getText();

            if (membercheck.isSelected() && bookcheck.isSelected()) {
                if (!"YYYY-MM-DD".equals(issue_date) && !"YYYY-MM-DD".equals(return_date)) {
                    massege.setText("");
                    int x = JOptionPane.showConfirmDialog(null, "CONFIRM ISSUENCE");
                    if (x == 0) {

                        String q = "INSERT INTO issue VALUES ('" + book_id + "','" + book_title + "','" + member_id + "','" + member_name + "','" + issue_date + "','" + return_date + "','" + details + "')";
                        try {
                            pst = con.prepareStatement(q);
                            pst.execute();
                            tableload();
                            reset();

                            pst = con.prepareStatement("DELETE FROM availablility WHERE book_id='" + book_id + "'");
                            pst.execute();

                        } catch (Exception e) {
                            massege.setText("Something Went Wrong");
                        }
                    }
                } else {
                    massege.setText("Please Enter Dates");
                }
            } else {
                massege.setText("Validation Failed");
            }
        }
    }//GEN-LAST:event_issueKeyPressed

    private void clearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clearKeyPressed

        int key = evt.getKeyCode();
        if (key == 39) {
            issue.requestFocus();
        } else if (key == 38) {
            detailsbox.requestFocus();
        } else if (key == 10) {
            reset();
        }
    }//GEN-LAST:event_clearKeyPressed

    private void searchtitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtitleActionPerformed

    private void searchnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchnameActionPerformed

    private void searchreturndateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchreturndateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchreturndateActionPerformed

    private void searchissuedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchissuedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchissuedateActionPerformed

    private void searchnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchnameKeyPressed
        int key = evt.getKeyCode();
        if (key == 10) {
            searchtitle.setText("");
            searchissuedate.setText("");
            searchreturndate.setText("");
            String name = searchname.getText();
            try {

                pst = con.prepareStatement("SELECT book_id,book_title,member_id,member_name,issue_date,return_date FROM issue WHERE member_name LIKE '%" + name + "%'");
                rs = pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_searchnameKeyPressed

    private void searchtitleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtitleKeyPressed
        int key = evt.getKeyCode();
        if (key == 10) {
            searchname.setText("");
            searchissuedate.setText("");
            searchreturndate.setText("");
            String name = searchtitle.getText();
            try {

                pst = con.prepareStatement("SELECT book_id,book_title,member_id,member_name,issue_date,return_date FROM issue WHERE book_title LIKE '%" + name + "%'");
                rs = pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_searchtitleKeyPressed

    private void searchissuedateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchissuedateKeyPressed
        int key = evt.getKeyCode();
        if (key == 10) {
            searchname.setText("");
            searchtitle.setText("");
            searchreturndate.setText("");
            String date1 = searchissuedate.getText();
            try {

                pst = con.prepareStatement("SELECT book_id,book_title,member_id,member_name,issue_date,return_date FROM issue WHERE issue_date LIKE '%" + date1 + "%'");
                rs = pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
                
            }
        }
    }//GEN-LAST:event_searchissuedateKeyPressed

    private void searchreturndateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchreturndateKeyPressed
        int key = evt.getKeyCode();
        if (key == 10) {
            searchname.setText("");
            searchissuedate.setText("");
            searchtitle.setText("");
            String date1 = searchreturndate.getText();
            try {

                pst = con.prepareStatement("SELECT book_id,book_title,member_id,member_name,issue_date,return_date FROM issue WHERE return_date LIKE '%" + date1 + "%'");
                rs = pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_searchreturndateKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //menu x=new menu();
        //x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bidbox;
    private javax.swing.JCheckBox bookcheck;
    private javax.swing.JButton clear;
    private javax.swing.JTextField detailsbox;
    private javax.swing.JLabel isbn;
    private javax.swing.JButton issue;
    private javax.swing.JTextField issuedatebox;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel massege;
    private javax.swing.JCheckBox membercheck;
    private javax.swing.JTextField midbox;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nic;
    private javax.swing.JTextField returndatebox;
    private javax.swing.JLabel risk;
    private javax.swing.JTextField searchissuedate;
    private javax.swing.JTextField searchname;
    private javax.swing.JTextField searchreturndate;
    private javax.swing.JTextField searchtitle;
    private javax.swing.JTable table;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
