/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainPackage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
//import java.time.LocalDate;
import javax.swing.JOptionPane;
//import net.proteanit.sql.DbUtils;

public class Login extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    //PreparedStatement pst1 = null;
    ResultSet rs = null;

    public Login() {
        initComponents();
        con = DBclass.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernamebox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordbox = new javax.swing.JPasswordField();
        sign = new javax.swing.JButton();
        massege = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN LIBRARY SYSTEM");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/WHAT-IS-THE-PURPOSE-OF-A-LIBRARY-MANAGEMENT-SYSTEM-min.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 530));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("USER NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        usernamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameboxActionPerformed(evt);
            }
        });
        usernamebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameboxKeyPressed(evt);
            }
        });
        getContentPane().add(usernamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 240, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        passwordbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordboxKeyPressed(evt);
            }
        });
        getContentPane().add(passwordbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 240, 30));

        sign.setBackground(new java.awt.Color(204, 0, 0));
        sign.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sign.setForeground(new java.awt.Color(255, 255, 255));
        sign.setText("SIGN");
        sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signActionPerformed(evt);
            }
        });
        sign.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                signKeyPressed(evt);
            }
        });
        getContentPane().add(sign, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        massege.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        massege.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(massege, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 260, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signKeyPressed
        if (evt.getKeyCode() == 10) {

            String username = usernamebox.getText();
            String password = new String(passwordbox.getPassword());

            try {

                pst = con.prepareStatement("SELECT * FROM login");
                rs = pst.executeQuery();
                rs.next();
                String u = rs.getString("username");
                String p = rs.getString("password");
                if (username.equals(u) && password.equals(p)) {
                    int y = JOptionPane.showConfirmDialog(null, "LOGIN SUCCESSFUL");
                    if (y == 0) {
                        menu x = new menu();
                        x.setVisible(true);
                        this.dispose();
                    }
                } else {
                    massege.setText("Invalid username or password !");
                }

            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_signKeyPressed

    private void signActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signActionPerformed

        String username = usernamebox.getText();
        String password = new String(passwordbox.getPassword());

        try {

            pst = con.prepareStatement("SELECT * FROM login");
            rs = pst.executeQuery();
            rs.next();
            String u = rs.getString("username");
            String p = rs.getString("password");
            if (username.equals(u) && password.equals(p)) {
                int y = JOptionPane.showConfirmDialog(null, "LOGIN SUCCESSFUL");
                if (y == 0) {
                    menu x = new menu();
                    x.setVisible(true);
                    this.dispose();
                }
            } else {
                massege.setText("Invalid username or password !");
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_signActionPerformed

    private void passwordboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordboxKeyPressed
        if (evt.getKeyCode() == 10) {
            sign.requestFocus();
        } else if (evt.getKeyCode() == 38) {
            usernamebox.requestFocus();
        }
    }//GEN-LAST:event_passwordboxKeyPressed

    private void usernameboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameboxKeyPressed
        if (evt.getKeyCode() == 10 || evt.getKeyCode() == 40) {
            passwordbox.requestFocus();
        }
    }//GEN-LAST:event_usernameboxKeyPressed

    private void usernameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel massege;
    private javax.swing.JPasswordField passwordbox;
    private javax.swing.JButton sign;
    private javax.swing.JTextField usernamebox;
    // End of variables declaration//GEN-END:variables
}
