/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainPackage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.time.*;
import java.util.*;
import java.text.SimpleDateFormat;

public class Return extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public Return() {
        initComponents();
        //risklable.setVisible(false);
        //combo.setVisible(false);
        //returnbox.setVisible(false);
        midbox.requestFocus();
        membercheck.setVisible(false);
        bookcheck.setVisible(false);
        con = DBclass.connect();
        tableload();

    }

    public void tableload() {
        try {
            String q = "SELECT id,member_id,date,issue_date,return_date FROM returntable";
            pst = con.prepareStatement(q);
            rs = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            massege.setText("Something Went Wrong");
        }
    }

    public void reset() {

        membercheck.setSelected(false);
        bookcheck.setSelected(false);
        membercheck.setVisible(false);
        bookcheck.setVisible(false);
        //returnbox.setVisible(true);
        //combo.setVisible(false);
        //risklable.setVisible(false);
        //returnbox.setVisible(false);
        combo.setVisible(true);
        risklable.setVisible(true);
        midbox.setText("");
        name.setText("");
        nic.setText("");
        risk.setText("");
        bidbox.setText("");
        titlebox.setText("");
        isbnbox.setText("");
        datebox.setText("");
        issuedatebox.setText("");
        returndatebox.setText("");
        massege.setText("");
        combo.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        midbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nic = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        risk = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        titlebox = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        isbnbox = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bidbox = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        bookcheck = new javax.swing.JCheckBox();
        membercheck = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        datebox = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        returndatebox = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        returnbox = new javax.swing.JButton();
        issuedatebox = new javax.swing.JLabel();
        massege = new javax.swing.JLabel();
        risklable = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RETURN BOOKS");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Member ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 74, 28));

        midbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midboxActionPerformed(evt);
            }
        });
        midbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                midboxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                midboxKeyReleased(evt);
            }
        });
        getContentPane().add(midbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 100, 210, 28));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Member Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 28));

        name.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 140, 210, 28));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("NIC");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 28, 28));

        nic.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 180, 210, 28));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Risk");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 28, 28));

        risk.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(risk, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 180, 40, 28));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Member Details");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 57, 330, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Book Details");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 266, 330, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Title");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 348, -1, 28));

        titlebox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(titlebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 348, 250, 28));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("ISBN");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 388, 61, 28));

        isbnbox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(isbnbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 388, 250, 28));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Book ID");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 308, 61, 28));

        bidbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidboxActionPerformed(evt);
            }
        });
        bidbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bidboxKeyPressed(evt);
            }
        });
        getContentPane().add(bidbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 308, 250, 28));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Date");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 484, 50, 28));

        bookcheck.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookcheck.setText("Book Validation");
        getContentPane().add(bookcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 428, -1, -1));

        membercheck.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        membercheck.setText("Member Validation");
        getContentPane().add(membercheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 216, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("*");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 94, 20, 40));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("*");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 314, 20, 20));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Book ID", "Member ID", "Date", "Issue Date", "Return Date"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 94, 790, 530));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Issued Date");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 524, -1, 28));

        datebox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(datebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 484, 230, 28));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Return Date");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 564, 70, 28));

        returndatebox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(returndatebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 564, 230, 28));

        clear.setBackground(new java.awt.Color(0, 0, 0));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        clear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clearKeyPressed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 604, 70, -1));

        jLabel23.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel23.setText("INQUIRY TABLE");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 64, -1, -1));

        returnbox.setBackground(new java.awt.Color(0, 0, 0));
        returnbox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        returnbox.setForeground(new java.awt.Color(255, 255, 255));
        returnbox.setText("RETURN");
        returnbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnboxActionPerformed(evt);
            }
        });
        returnbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                returnboxKeyPressed(evt);
            }
        });
        getContentPane().add(returnbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 604, 80, -1));

        issuedatebox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(issuedatebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 524, 230, 28));
        getContentPane().add(massege, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 604, 170, 20));

        risklable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        risklable.setText("Risk");
        getContentPane().add(risklable, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, 30));

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 444, -1, -1));

        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 44, 870, 610));

        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 44, 390, 610));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 660, 90, 10));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 304, 20, 50));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("MENU");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("RETURN BOOKS");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 150, 29));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void midboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midboxActionPerformed

    private void midboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_midboxKeyPressed

        String member_id = midbox.getText();
        int key = evt.getKeyCode();
        if (key == 10) {
            try {
                String q = "SELECT member_name FROM issue WHERE member_id='" + member_id + "'";
                pst = con.prepareStatement(q);
                rs = pst.executeQuery();
                rs.next();
                name.setText(rs.getString("member_name"));

                PreparedStatement pst1 = con.prepareStatement("SELECT id,risk FROM members WHERE member_id='" + member_id + "'");
                ResultSet rs1 = pst1.executeQuery();
                rs1.next();
                nic.setText(rs1.getString("id"));
                risk.setText(rs1.getString("risk"));
                membercheck.setVisible(true);
                bidbox.requestFocus();

            } catch (Exception e) {
                name.setText("");
                nic.setText("");
                risk.setText("");
                membercheck.setSelected(false);
                membercheck.setVisible(false);
            }
        }
    }//GEN-LAST:event_midboxKeyPressed

    private void bidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bidboxActionPerformed

    private void bidboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bidboxKeyPressed

        String book_id = bidbox.getText();
        int key = evt.getKeyCode();
        if (key == 10) {
            try {
                String q = "SELECT book_title FROM issue WHERE book_id='" + book_id + "'";
                pst = con.prepareStatement(q);
                rs = pst.executeQuery();
                rs.next();
                titlebox.setText(rs.getString("book_title"));

                PreparedStatement pst1 = con.prepareStatement("SELECT isbn FROM books WHERE book_id='" + book_id + "'");
                ResultSet rs1 = pst1.executeQuery();
                rs1.next();

                isbnbox.setText(rs1.getString("isbn"));
                bookcheck.setVisible(true);

                pst = con.prepareStatement("SELECT issue_date,return_date FROM issue WHERE book_id='" + bidbox.getText() + "' AND member_id='" + midbox.getText() + "'");
                rs = pst.executeQuery();
                rs.next();
                String d = LocalDate.now().toString();
                String i = rs.getString("issue_date");
                String r = rs.getString("return_date");
                datebox.setText(d);
                issuedatebox.setText(i);
                returndatebox.setText(r);

                /*SimpleDateFormat s = new SimpleDateFormat("YYYY-mm-dd");
                Date d1 = s.parse(d);
                Date d2 = s.parse(r);
                
                if (d1.after(d2)) {

                    risklable.setVisible(true);
                    combo.setVisible(true);

                } else {
                    returnbox.setVisible(true);
                    returnbox.requestFocus();

                }*/
            } catch (Exception e) {
                titlebox.setText("");
                isbnbox.setText("");
                bookcheck.setSelected(false);
                bookcheck.setVisible(false);
                //massege.setText("Something Went Wrong");

            }
        }

    }//GEN-LAST:event_bidboxKeyPressed

    private void midboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_midboxKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_midboxKeyReleased

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        reset();

    }//GEN-LAST:event_clearActionPerformed

    private void returnboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnboxActionPerformed

        String member_id = midbox.getText();
        String book_id = bidbox.getText();
        String title = titlebox.getText();
        String isbn = isbnbox.getText();
        String today = datebox.getText();
        String issuedate = issuedatebox.getText();
        String returndate = returndatebox.getText();

        if (membercheck.isSelected() && bookcheck.isSelected()) {
            int x = JOptionPane.showConfirmDialog(null, "CONFIRM RETURN");
            if (x == 0) {

                try {

                    pst = con.prepareStatement("DELETE FROM issue WHERE book_id='" + book_id + "' AND member_id='" + member_id + "'");
                    pst.execute();

                    PreparedStatement pst1 = con.prepareStatement("INSERT INTO availablility VALUES ('" + book_id + "','" + isbn + "','" + title + "')");
                    pst1.execute();

                    PreparedStatement pst2 = con.prepareStatement("INSERT INTO returntable VALUES ('" + book_id + "','" + member_id + "','" + today + "','" + issuedate + "','" + returndate + "')");
                    pst2.execute();
                    tableload();
                    reset();

                } catch (Exception e) {
                    massege.setText("Something Went Wrong");
                }

            }
        } else {
            massege.setText("Validation Failed");
        }
    }//GEN-LAST:event_returnboxActionPerformed

    private void returnboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_returnboxKeyPressed

        if (evt.getKeyCode() == 10) {

            String member_id = midbox.getText();
            String book_id = bidbox.getText();
            String title = titlebox.getText();
            String isbn = isbnbox.getText();
            String today = datebox.getText();
            String issuedate = issuedatebox.getText();
            String returndate = returndatebox.getText();

            if (membercheck.isSelected() && bookcheck.isSelected()) {
                int x = JOptionPane.showConfirmDialog(null, "CONFIRM RETURN");
                if (x == 0) {

                    try {

                        pst = con.prepareStatement("DELETE FROM issue WHERE book_id='" + book_id + "' AND member_id='" + member_id + "'");
                        pst.execute();

                        PreparedStatement pst1 = con.prepareStatement("INSERT INTO availablility VALUES ('" + book_id + "','" + isbn + "','" + title + "')");
                        pst1.execute();

                        PreparedStatement pst2 = con.prepareStatement("INSERT INTO returntable VALUES ('" + book_id + "','" + member_id + "','" + today + "','" + issuedate + "','" + returndate + "')");
                        pst2.execute();
                        tableload();
                        reset();

                    } catch (Exception e) {
                        massege.setText("Something Went Wrong");
                    }

                }
            } else {
                massege.setText("Validation Failed");
            }

        } else if (evt.getKeyCode() == 37) {
            clear.requestFocus();
        }

    }//GEN-LAST:event_returnboxKeyPressed

    private void clearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clearKeyPressed
        if (evt.getKeyCode() == 10) {
            reset();
        } else if (evt.getKeyCode() == 39) {
            returnbox.requestFocus();
        }
    }//GEN-LAST:event_clearKeyPressed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed

        if (membercheck.isSelected() && bookcheck.isSelected()) {
            String y = combo.getSelectedItem().toString();
            String d = LocalDate.now().toString();
            int x = JOptionPane.showConfirmDialog(null, "CONFIRM RISK UPDATION");
            if (x == 0) {
                try {

                    PreparedStatement pst4 = con.prepareStatement("UPDATE members SET risk = '" + y + "' WHERE member_id='" + midbox.getText() + "'");
                    pst4.execute();
                    PreparedStatement pst3 = con.prepareStatement("INSERT INTO risk VALUES ('" + d + "','" + midbox.getText() + "','" + name.getText() + "','" + risk.getText() + "','" + y + "')");
                    pst3.execute();
                    combo.setVisible(false);
                    risklable.setVisible(false);
                    if (Integer.parseInt(y) == 5) {

                        PreparedStatement pst7 = con.prepareStatement("SELECT membership_date,name,id FROM members WHERE member_id='" + midbox.getText() + "'");
                        rs = pst7.executeQuery();
                        rs.next();
                        String fromdate = rs.getString("membership_date");
                        String name = rs.getString("name");
                        String nic = rs.getString("id");

                        PreparedStatement pst6 = con.prepareStatement("INSERT INTO deletedmember VALUES ('" + name + "','" + nic + "','" + fromdate + "','" + d + "')");
                        pst6.execute();

                        PreparedStatement pst5 = con.prepareStatement("DELETE FROM members WHERE member_id='" + midbox.getText() + "'");
                        pst5.execute();

                    }
                    //combo.setVisible(false);
                    //risklable.setVisible(false);
                    //returnbox.setVisible(true);

                } catch (Exception e) {
                    massege.setText("Something Went Wrong");
                    //System.out.println(e);
                }

            } else {
                combo.setSelectedIndex(0);
            }
        } else {
            combo.setSelectedIndex(0);
        }
    }//GEN-LAST:event_comboActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //menu x=new menu();
        //x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField bidbox;
    public static javax.swing.JCheckBox bookcheck;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox<String> combo;
    public static javax.swing.JLabel datebox;
    public static javax.swing.JLabel isbnbox;
    public static javax.swing.JLabel issuedatebox;
    private javax.swing.JButton jButton5;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel17;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    public static javax.swing.JLabel jLabel24;
    public static javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel massege;
    public static javax.swing.JCheckBox membercheck;
    public static javax.swing.JTextField midbox;
    public static javax.swing.JLabel name;
    public static javax.swing.JLabel nic;
    private javax.swing.JButton returnbox;
    public static javax.swing.JLabel returndatebox;
    public static javax.swing.JLabel risk;
    private javax.swing.JLabel risklable;
    public static javax.swing.JTable table;
    public static javax.swing.JLabel titlebox;
    // End of variables declaration//GEN-END:variables
}
